# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: AMD-Ryzen-3-3200U
  
resources:
  repositories:
    - repository: github_repo
      type: github
      name: jasonfigueroa/DemoRazorApp
      endpoint: DemoRazorApp-GitHub # Your service connection name


#variables:
#  gitHubRepoUrl: 'https://github.com/jasonfigueroa/DemoRazorApp.git'

steps:
- checkout: self
  displayName: 'Checkout Azure Repo'
  fetchDepth: 0  # Get all history
  
- task: Bash@3
  displayName: 'Configure Git'
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "azuredevops@jasonfigueroa.com"
      git config --global user.name "Azure DevOps Mirror"

- task: Bash@3
  displayName: 'Sync to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      echo "Configuring GitHub remote..."
      git remote remove github 2>/dev/null || true
      
      # Using the service connection
      git remote add github "https://x-token-auth:${SYSTEM_ACCESSTOKEN}@github.com/jasonfigueroa/DemoRazorApp.git"
      
      echo "Pushing to GitHub..."
      if ! git push github --all -f; then
        echo "Error: Failed to push branches to GitHub"
        exit 1
      fi
      
      if ! git push github --tags -f; then
        echo "Error: Failed to push tags to GitHub"
        exit 1
      fi
      
      echo "Sync completed successfully!"
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
