# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: AMD Ryzen 3 3200U

variables:
  gitHubRepoUrl: 'https://github.com/jasonfigueroa/DemoRazorApp.git'

steps:
- checkout: self
  displayName: 'Checkout branch'

- script: |
    echo "Setting up Git for mirroring to GitHub..."
    git config --global user.email "azuredevops@jasonfigueroa.com"
    git config --global user.name "Azure DevOps Mirror"

    # Check if 'github' remote exists and remove it if it does
    if git remote get-url github > /dev/null 2>&1; then
      echo "Remote 'github' already exists. Removing it..."
      git remote remove github
    fi

    # Add GitHub as a remote using the PAT for authentication
    git remote add github https://$(GITHUB_PAT_VAR)@github.com/jasonfigueroa/DemoRazorApp.git

    echo "Mirroring all branches and tags to GitHub..."
    git push github --all
    git push github --tags
  displayName: 'Mirror to GitHub'
  env:
    GITHUB_PAT_VAR: $(GitHubPat) # Map the Azure DevOps variable to an environment variable
